e-commerce-project/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using e_commerce_project.viewModels.categories;
using e_commerce_project.Models;
using e_commerce_project.Repos;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;

namespace e_commerce_project.Controllers
{
    [Authorize(Roles = "Admin,Editor")]
    public class CategoryController : Controller
    {
        ICategoryRepo cat;
        IWebHostEnvironment WebHostEnvironment;
        public CategoryController(ICategoryRepo _cat,IWebHostEnvironment _WebHostEnvironment)
        {
            cat= _cat;
            WebHostEnvironment=_WebHostEnvironment;
        }

        public IActionResult isUnique(string Name)
        {
            return cat.FindByName(Name) == true ? Json(false):Json(true);
        }


        public IActionResult Index()
        {
            List<Category> cats = cat.GetAll();
            return View(cats);
        }

        public IActionResult New()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveNew(AddCategoryVM cat)
        {
            if (ModelState.IsValid == false)
            {
                return View("New",cat);
            }

            #region store image on server
            string categoriesImages = Path.Combine(WebHostEnvironment.WebRootPath, "categoriesImages");
            string UniqueimgName = Guid.NewGuid().ToString() + "_" + cat.img.FileName;
            string imgPath = Path.Combine(categoriesImages, UniqueimgName);
            using (var fileStream = new FileStream(imgPath, FileMode.Create))
            {
                cat.img.CopyTo(fileStream);
                fileStream.Close();
            }
            #endregion

            this.cat.Insert(new Category() { Name=cat.Name,img= UniqueimgName, Description=cat.Description});
            return RedirectToAction("Index");
        }


        public IActionResult Edit(int id)
        {
            Category catToEdit = cat.FindById(id);
            if(catToEdit != null)
            {
                return View(catToEdit);
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveEdit(Category cat)
        {
            if (ModelState.IsValid==false)
            {
                return View("Edit",cat);
            }
            this.cat.Edit(cat.Id, cat);
            return RedirectToAction("Index");
        }

        public IActionResult delete(int id)
        {
            this.cat.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

e-commerce-project/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using e_commerce_project.Repos;
using Microsoft.AspNetCore.Authorization;
using e_commerce_project.Models.postRequestsModels;
using e_commerce_project.Models;
using System.Collections.Generic;
using System.Linq;
namespace e_commerce_project.Controllers
{
    [Authorize(Roles = "Admin,Editor")]
    public class OrderController : Controller
    {
        private readonly IOrderRepo orderRepo;
        private readonly IorderProductRepo iorderProductRepo;
        public OrderController(IOrderRepo orderRepo, IorderProductRepo iorderProductRepo)
        {
            this.orderRepo = orderRepo;
            this.iorderProductRepo = iorderProductRepo;
        }
        public IActionResult Index()
        {
            var orders = orderRepo.allOrders();
            return View(orders);
        }
        [HttpPost]
        public IActionResult editAddress(int id,[FromBody] Address address)
        {
            orderRepo.Edit(id, address);
            return Json(new { });
        }

        public IActionResult getOrderDetails(int id)
        {
            List<OrderProduct> products = iorderProductRepo.getOrderProducts(id).ToList();
            return View(products);
        }

        public IActionResult orderByDate(string type)
        {
            return Json(orderRepo.orderByDate(type));
        }
        public  IActionResult orderByTotal(string type)
        {
            List<Order> orders = orderRepo.orderByTotal(type);
            return Json(orders);
        }
        
        public IActionResult CountOfSalesOfEachProduct()
        {
            var q = orderRepo.CountOfSalesOfEachProduct();
            return Json(orderRepo.CountOfSalesOfEachProduct());
        }
    }
}

e-commerce-project/Controllers/adminProductController.cs
using Microsoft.AspNetCore.Mvc;
using e_commerce_project.Repos;
using e_commerce_project.Models;
using e_commerce_project.viewModels.Products;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System;
using Microsoft.AspNetCore.Authorization;

namespace e_commerce_project.Controllers
{
    [Authorize(Roles = "Admin,Editor")]
    public class productController : Controller
    {
        private readonly IProductRepo product;
        private readonly ICategoryRepo category;
        IWebHostEnvironment WebHostEnvironment;

        public productController(IProductRepo product, ICategoryRepo category, IWebHostEnvironment WebHostEnvironment)
        {
            this.product = product;
            this.category = category;
            this.WebHostEnvironment = WebHostEnvironment;
        }

        public IActionResult Index()
        {
            var allproduct = product.GetproductandCategory();
            return View(allproduct);
        }
        public IActionResult Delete(int id)
        {
            this.product.Delete(id);
            return RedirectToAction("Index");
        }
        public IActionResult New()
        {
            ViewBag.AllCategories = this.category.GetAll();
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveNew(AddProductVM pro)
        {
            if (ModelState.IsValid == false)
            {
                ViewBag.AllCategories = this.category.GetAll();
                return View("New", pro);
            }

            #region store image on server
            string productsImages = Path.Combine(WebHostEnvironment.WebRootPath, "productImages");
            string UniqueimgName = Guid.NewGuid().ToString() + "_" + pro.img.FileName;
            string imgPath = Path.Combine(productsImages, UniqueimgName);
            using (var fileStream = new FileStream(imgPath, FileMode.Create))
            {
                pro.img.CopyTo(fileStream);
                fileStream.Close();
            }
            #endregion
            this.product.Insert(new Product() { Name = pro.Name, img = UniqueimgName, Price = pro.Price, Description = pro.Description, CategoryId = pro.CategoryId });
            return RedirectToAction("Index");
        }
    
        
        public IActionResult Edit(int id)
        {
            var oldProduct = this.product.FindById(id);
            if (oldProduct != null)
            {
                ViewBag.AllCategories = this.category.GetAll();
                return View("Edit",oldProduct);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult SaveEdit(Product product)
        {
            if (ModelState.IsValid == false)
            {
                return View("Edit", product);
            }
            this.product.Edit(product.Id, product);
            return RedirectToAction("Index");
        }
    }
}

e-commerce-project/Views/Shared/_Admin.cshtml
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Sweet Alert -->
    <link type="text/css" href="/AdminLayoutTemplate/sweetalert2.min.css" rel="stylesheet">

    <!-- Notyf -->
    <link type="text/css" href="/AdminLayoutTemplate/notyf.min.css" rel="stylesheet">

    <!-- Volt CSS -->
    <link type="text/css" href="/AdminLayoutTemplate/volt.css" rel="stylesheet">

    <link type="text/css" href="/AdminLayoutTemplate/myStyle.css" rel="stylesheet">
    <link type="text/css" href="/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    @RenderSection("MyStyles",false)
</head>
<body>
    <div>
        @Html.Partial("_aside")
        <main class="content">
                @RenderBody()
         </main>
    </div>
        <script src="/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        @RenderSection("MyScripts",false)
</body>
</html>

e-commerce-project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - e_commerce_project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    
    <!-- css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/tomik23/autocomplete@1.8.4/dist/css/autocomplete.min.css"/>

    <!-- js -->
    <script src="https://cdn.jsdelivr.net/gh/tomik23/autocomplete@1.8.4/dist/js/autocomplete.min.js"></script>
          
    
    @RenderSection("MyStyles",false)
    @Html.Partial("/wwwroot/shopProductTemmplate/_design.cshtml");
</head>
<body>

 @Html.Partial("/wwwroot/shopProductTemmplate/_header.cshtml");
 @Html.Partial("/wwwroot/shopProductTemmplate/_pageHeader.cshtml");
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
 @Html.Partial("/wwwroot/shopProductTemmplate/_footer.cshtml");
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
    @RenderSection("MyScript",false)

</body>
</html>

e-commerce-project/Views/Shared/_aside.cshtml
<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
  <div class="sidebar-inner px-4 pt-3">
    <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
      <div class="d-flex align-items-center">
        <div class="avatar-lg me-4">
          <img src="../../assets/img/team/profile-picture-3.jpg" class="card-img-top rounded-circle border-white"
            alt="Bonnie Green">
        </div>
        <div class="d-block">
          <h2 class="h5 mb-3">Hi, Jane</h2>
          <a href="../../pages/examples/sign-in.html" class="btn btn-secondary btn-sm d-inline-flex align-items-center">
            <svg class="icon icon-xxs me-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>            
            Sign Out
          </a>
        </div>
      </div>
      <div class="collapse-close d-md-none">
        <a href="#sidebarMenu" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true"
            aria-label="Toggle navigation">
            <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          </a>
      </div>
    </div>
    <ul class="nav flex-column pt-3 pt-md-0">
          <li class="nav-item  active ">
            <a asp-action="Index" asp-controller="product" class="nav-link">
              <span class="sidebar-text">Products</span>
            </a>
          </li>
          <li class="nav-item  active ">
            <a asp-action="Index" asp-controller="Category" class="nav-link">
              <span class="sidebar-text">Categories</span>
            </a>
          </li>
            @{
                
                if (User.Identity.IsAuthenticated == true)
                {
                    if (User.IsInRole("Admin")==true)
                    {
                         <li class="nav-item active ">
                            <a asp-action="Editors" asp-controller="Editor" class="nav-link">
                              <span class="sidebar-text">Editors</span>
                            </a>
                         </li>
                    }
                }

            }
            <li class="nav-item active ">
                            <a asp-action="Index" asp-controller="Order" class="nav-link">
                              <span class="sidebar-text">orders</span>
                            </a>
            </li>

      <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
          <li class="nav-item  active ">
            <a asp-action="signout" asp-controller="Account" class="nav-link">
              <span class="sidebar-text">sign out</span>
            </a>
          </li>
          <li class="nav-item  active ">
            <a asp-action="Index" asp-controller="Home" class="nav-link">
              <span class="sidebar-text">user view</span>
            </a>
          </li>
    </ul>
  </div>
</nav>

e-commerce-project/Views/Shared/_main.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @RenderSection("MyStyles",false)
</head>
<body>
    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("MyScript",false)
</body>
</html>