e-commerce-project/Controllers/HomeController.cs
using System.Diagnostics;
using e_commerce_project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Microsoft.AspNetCore.Hosting;

namespace e_commerce_project.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;


        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

e-commerce-project/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using e_commerce_project.Repos;
using System.Collections.Generic;
using e_commerce_project.Models;
namespace e_commerce_project.Controllers
{
    public class ShowProductController : Controller
    {
        IProductRepo productRepo;
        private readonly IorderProductRepo orderProductRepo;

        public ShowProductController(IProductRepo productRepo,IorderProductRepo orderProductRepo)
        {
            this.productRepo = productRepo;
            this.orderProductRepo = orderProductRepo;
        }
        
        public IActionResult Products()
        {
            List<Product> products=productRepo.GetAll();
            return View(products);
        }

        public IActionResult getProductById(int id)
        {
            Product product=productRepo.FindById(id);
            return View(product);
        }


        public IActionResult search(string name)
        {
            List<Product> products = productRepo.searchByName(name);
            return Json(products);
        }
        public IActionResult getProductsBYcategoryId(int id)
        {
            List<Product> products = productRepo.getProductsBYcategoryId(id);
            return View("Products",products);
        }

        public IActionResult filterByPrice(decimal price)
        {
            return Json(productRepo.getProductsBYPrice(price));
        }

        public IActionResult getProductCount()
        {
            return Json(orderProductRepo.getProductCount());
        }
        
        public IActionResult getProductTotalPrice()
        {
            return Json(orderProductRepo.getProductTotalPrice());
        }
    }
}

e-commerce-project/Views/Home/Index.cshtml
@{
    Layout= "_Layout";
}

<div class="owl-carousel owl-theme">
    <a asp-action="getProductsBYcategoryId" asp-controller="ShowProduct" asp-route-id=1>
        <div style="background-image:url(/categoriesImages/CHAIR.webp)" class="item"></div>
    </a>
    <a asp-action="getProductsBYcategoryId" asp-controller="ShowProduct" asp-route-id=2>
        <div style="background-image:url(/categoriesImages/DESK.webp);" class="item"></div>
    </a>
    <a asp-action="getProductsBYcategoryId" asp-controller="ShowProduct" asp-route-id=4>
         <div style="background-image:url(/categoriesImages/LIGHTING.webp);" class="item"></div>
    </a>
    <a asp-action="getProductsBYcategoryId" asp-controller="ShowProduct" asp-route-id=3>
       <div style="background-image:url(/categoriesImages/TABLE.webp);" class="item"></div>
    </a>
</div>








@section MyScript{
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.js" integrity="sha512-gY25nC63ddE0LcLPhxUJGFxa2GoIyA5FLym4UJqHDEMHjp8RET6Zn/SHo1sltt3WuVtqfyxECP38/daUc/WVEA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
$(document).ready(function(){
    $(".owl-carousel").owlCarousel();
});
$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay:true,
    autoplayHoverPause:true,
    slideTransition: 'linear',
    autoplaySpeed: 6000,
    smartSpeed: 6000,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:4
        }
    }
})
fetch("http://localhost:3000").then(data=>data.json()).
then(data=>{
    console.log(data)
})
</script>
}
@section MyStyles{
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.css" integrity="sha512-UTNP5BXLIptsaj5WdKFrkFov94lDx+eBvbKyoe1YAfjeRPC+gT5kyZ10kOHCfNZqEui1sxmqvodNUx3KbuYI/A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<style>
    .owl-nav{
        display:none;
    }
    .item{
        height:500px;
        background-image:url(https://source.unsplash.com/random?1=2);
        background-position:center;
        background-size:cover;
        background-repeat:no-repeat;
    }
</style>
}